//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRN
    {
        public GRN()
        {
            this.GRNDetails = new HashSet<GRNDetail>();
        }
    
        public string Name { get; set; }
        public long ID { get; set; }
        public Nullable<long> DesignationID { get; set; }
        public string Lab { get; set; }
        public string Project { get; set; }
        public string GRNNo { get; set; }
        public string SuplyOrderNo { get; set; }
        public Nullable<System.DateTime> SuplyDate { get; set; }
        public Nullable<System.DateTime> GRNDate { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAddress { get; set; }
    
        public virtual ICollection<GRNDetail> GRNDetails { get; set; }
    }
}
