//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRNDetail
    {
        public long ID { get; set; }
        public string LeadgerPage { get; set; }
        public string Description { get; set; }
        public string AU { get; set; }
        public Nullable<long> QTYCreated { get; set; }
        public Nullable<long> QTYRecived { get; set; }
        public string Rate { get; set; }
        public string TotalValue { get; set; }
        public Nullable<long> GRNID { get; set; }
    
        public virtual GRN GRN { get; set; }
    }
}
