//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryManagementSystemEntities : DbContext
    {
        public InventoryManagementSystemEntities()
            : base("name=InventoryManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GRNDetail> GRNDetails { get; set; }
        public DbSet<GRN> GRNs { get; set; }
        public DbSet<RefDesignation> RefDesignations { get; set; }
        public DbSet<RefUser> RefUsers { get; set; }
        public DbSet<RequisitionFormDetail> RequisitionFormDetails { get; set; }
        public DbSet<RequisitionForm> RequisitionForms { get; set; }
        public DbSet<ReturnVoucherDetail> ReturnVoucherDetails { get; set; }
        public DbSet<ReturnVoucher> ReturnVouchers { get; set; }
        public DbSet<StokeRegister> StokeRegisters { get; set; }
    }
}
