//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class InventoryManagementSystemEntities : DbContext
    {
        public InventoryManagementSystemEntities()
            : base("name=InventoryManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GRNDetail> GRNDetails { get; set; }
        public DbSet<GRN> GRNs { get; set; }
        public DbSet<RefDesignation> RefDesignations { get; set; }
        public DbSet<RefUser> RefUsers { get; set; }
        public DbSet<RequisitionFormDetail> RequisitionFormDetails { get; set; }
        public DbSet<RequisitionForm> RequisitionForms { get; set; }
        public DbSet<ReturnVoucherDetail> ReturnVoucherDetails { get; set; }
        public DbSet<ReturnVoucher> ReturnVouchers { get; set; }
        public DbSet<StokeRegister> StokeRegisters { get; set; }
    
        public virtual ObjectResult<IssueVoucherReport_Result> IssueVoucherReport(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IssueVoucherReport_Result>("IssueVoucherReport", nameParameter);
        }
    
        public virtual ObjectResult<ReturnVoucherReport_Result> ReturnVoucherReport(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReturnVoucherReport_Result>("ReturnVoucherReport", nameParameter);
        }
    }
}
