//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefDesignation
    {
        public RefDesignation()
        {
            this.RequisitionForms = new HashSet<RequisitionForm>();
            this.ReturnVouchers = new HashSet<ReturnVoucher>();
        }
    
        public long ID { get; set; }
        public string Description { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public string EntryUserID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<RequisitionForm> RequisitionForms { get; set; }
        public virtual ICollection<ReturnVoucher> ReturnVouchers { get; set; }
    }
}
