//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefUser
    {
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IdentityNo { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNumber { get; set; }
        public string Password { get; set; }
        public string UserProfileImage { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> IsSuperAdmin { get; set; }
        public Nullable<bool> IsExternal { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public long EntryUserID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> ProjectID { get; set; }
    }
}
