//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionForm
    {
        public RequisitionForm()
        {
            this.RequisitionFormDetails = new HashSet<RequisitionFormDetail>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> DesignationID { get; set; }
        public string Lab { get; set; }
        public string Project { get; set; }
        public string SifNo { get; set; }
        public Nullable<bool> IsConsumable { get; set; }
        public string SignatureOfInditor { get; set; }
        public string SignatureOfStoreKeeper { get; set; }
    
        public virtual RefDesignation RefDesignation { get; set; }
        public virtual ICollection<RequisitionFormDetail> RequisitionFormDetails { get; set; }
    }
}
