//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokeRegister
    {
        public long ID { get; set; }
        public string Particular { get; set; }
        public string Date { get; set; }
        public string Folio { get; set; }
        public string QTYRecipt { get; set; }
        public string QTYIssued { get; set; }
        public string Balance { get; set; }
        public string Remarks { get; set; }
    }
}
